# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: AngularDoc
description: > # this means to ignore newlines until "baseurl:"
  Architectural analysis and visualization for Angular 2 projects or Angular 1.x projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://angulardoc.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false

sass:
  sass_dir: _sass
  style: compressed
  
#bootstrap:
 # assets: true

# theme: minima
# End

# Gem settings
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-youtube
  # - jekyll-bootstrap-sass

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
# End

# Github metadata settings
repository: AngularDoc/angulardoc.github.io
# End

# jekyll-seo-tag settings
social:
  name: AngularDoc
  links:
    - https://twitter.com/angulardocio
    - https://github.com/AngularDoc

logo: /assets/img/logo/DAlogo.png

twitter:
  username: angulardocio
#End

# Date format settings
date_format: "%b %-d, %Y"
# End

# Site permalink settings
permalink: /:title/
# End

# Collections settings
collections:
  documentation:
    output: true
    permalink: /:collection/:path
# End

# plugins
# plugins_dir: 
#   jekyll-youtube
# end

# Site menu settings
menu:
  - title: "Products"
    url: "/products"
  - title: "Services"
    url: "/services"
  - title: "Resources"
    url: "/resources"
  - title: "Downloads"
    url: "/downloads"
# End

category_order:
  - 'Getting-started'
  - 'Fundamentals'
  - 'TipCalc Tutorial'
  - 'Platform specifics'
  - 'Upgrading'
  - 'Testing'
  - 'Contributing'
  - 'Licensing'